# This configuration is intended for development purpose, it's **your** responsibility to harden it for production
name: absaugdtmicrosrvcgateway
services:
  app:
    image: absaugdtmicrosrvcgateway
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,api-docs
      - MANAGEMENT_PROMETHEUS_METRICS_EXPORT_ENABLED=true
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/eureka
      - SPRING_CLOUD_CONFIG_URI=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/config
      - SPRING_R2DBC_URL=r2dbc:postgresql://postgresql:5432/AbsaUGDTMicrosrvcGateway
      - SPRING_LIQUIBASE_URL=jdbc:postgresql://postgresql:5432/AbsaUGDTMicrosrvcGateway
      - SPRING_ELASTICSEARCH_URIS=http://elasticsearch:9200
      - SPRING_CLOUD_STREAM_KAFKA_BINDER_BROKERS=kafka:9092
    ports:
      - 127.0.0.1:9050:9050
    healthcheck:
      test:
        - CMD
        - curl
        - -f
        - http://localhost:9050/management/health
      interval: 5s
      timeout: 5s
      retries: 40
    depends_on:
      postgresql:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy
      jhipster-registry:
        condition: service_healthy
  postgresql:
    extends:
      file: ./postgresql.yml
      service: postgresql
  elasticsearch:
    extends:
      file: ./elasticsearch.yml
      service: elasticsearch
  jhipster-registry:
    extends:
      file: ./jhipster-registry.yml
      service: jhipster-registry
  kafka:
    extends:
      file: ./kafka.yml
      service: kafka
  zookeeper:
    extends:
      file: ./kafka.yml
      service: zookeeper
