export enum ModeOfPayment {
  CASH = 'CASH',

  RTGS = 'RTGS',

  INTERNAL_TRANSFER = 'INTERNAL_TRANSFER',

  CARD = 'CARD',

  BANK_TRANSFER = 'BANK_TRANSFER',

  PAYMENT_CARD = 'PAYMENT_CARD',

  PAYMENT_BANK_TRANSFER = 'PAYMENT_BANK_TRANSFER',
}
