import dayjs from 'dayjs';
import { IDTransaction } from 'app/shared/model/d-transaction.model';
import { TranStatus } from 'app/shared/model/enumerations/tran-status.model';
import { Currency } from 'app/shared/model/enumerations/currency.model';
import { Channel } from 'app/shared/model/enumerations/channel.model';

export interface IAmolDTransactions {
  id?: number;
  absaTranRef?: string | null;
  billerId?: string | null;
  dtDTransactionId?: string | null;
  amolDTransactionId?: string | null;
  transactionReferenceNumber?: string | null;
  token?: string | null;
  transferId?: string | null;
  externalTxnId?: string | null;
  customerReference?: string | null;
  debitAccountNumber?: string;
  creditAccountNumber?: string;
  debitAmount?: number;
  creditAmount?: number | null;
  transactionAmount?: number | null;
  debitDate?: string | null;
  creditDate?: string | null;
  status?: TranStatus | null;
  settlementDate?: string | null;
  debitCurrency?: Currency;
  timestamp?: string;
  phoneNumber?: string;
  email?: string;
  payerName?: string | null;
  payerAddress?: string | null;
  payerEmail?: string | null;
  payerPhoneNumber?: string | null;
  payerNarration?: string | null;
  payerBranchId?: string | null;
  beneficiaryName?: string | null;
  beneficiaryAccount?: string | null;
  beneficiaryBranchId?: string | null;
  beneficiaryPhoneNumber?: string | null;
  tranStatus?: TranStatus | null;
  narration1?: string | null;
  narration2?: string | null;
  narration3?: string | null;
  taxAmount?: number | null;
  taxGLAccount?: string | null;
  taxNarration?: string | null;
  internalErrorCode?: string | null;
  externalErrorCode?: string | null;
  payeeBranchId?: string | null;
  payeeProductInstanceReference?: string | null;
  payeeProductCode?: string | null;
  payeeProductName?: string | null;
  payeeProductDescription?: string | null;
  payeeProductUnitOfMeasure?: string | null;
  payeeProductQuantity?: string | null;
  subCategoryCode?: string | null;
  payerBankCode?: string | null;
  payerBankName?: string | null;
  payerBankAddress?: string | null;
  payerBankCity?: string | null;
  payerBankState?: string | null;
  payerBankCountry?: string | null;
  payerBankPostalCode?: string | null;
  checkerId?: string | null;
  remittanceInformation?: string | null;
  paymentChannelCode?: Channel | null;
  feeAmount?: number | null;
  feeGLAccount?: string | null;
  feeNarration?: string | null;
  tranFreeField1?: string | null;
  tranFreeField2?: string | null;
  tranFreeField3?: string | null;
  tranFreeField4?: string | null;
  tranFreeField5?: string | null;
  tranFreeField6?: string | null;
  tranFreeField7?: string | null;
  tranFreeField8?: string | null;
  tranFreeField9?: string | null;
  tranFreeField10?: string | null;
  tranFreeField11?: string | null;
  tranFreeField12?: string | null;
  tranFreeField13?: string | null;
  tranFreeField14?: string | null;
  tranFreeField15?: string | null;
  tranFreeField16?: string | null;
  tranFreeField17?: string | null;
  tranFreeField18?: number | null;
  tranFreeField19?: number | null;
  tranFreeField20?: boolean | null;
  tranFreeField21?: string | null;
  tranFreeField22?: string | null;
  tranFreeField23ContentType?: string | null;
  tranFreeField23?: string | null;
  tranFreeField24?: string | null;
  responseCode?: string | null;
  responseMessage?: string | null;
  responseDetails?: string | null;
  transferReferenceId?: string | null;
  transferStatus?: string | null;
  responseDateTime?: string | null;
  createdAt?: string | null;
  createdBy?: string | null;
  updatedAt?: string | null;
  updatedBy?: string | null;
  dTransaction?: IDTransaction | null;
}

export const defaultValue: Readonly<IAmolDTransactions> = {
  tranFreeField20: false,
};
